export const PEERS_CDN: object = {
  ECO_CDN: [
    '//cdn.jsdelivr.net/npm/hls.js@0.14.16',
    '//cdn.jsdelivr.net/npm/ecocdn/videojs-hlsjs-plugin.min.js',
    '//cdn.jsdelivr.net/npm/ecocdn/fptplay/hlsjs-ecocdn.min.js',
  ],
  PEER5: [
    '//api.peer5.com/peer5.js?id=dx8k4sjscbht91dmv1rl',
    '//api.peer5.com/peer5.videojs6.plugin.js',
  ],
};
export const LANGUAGE: object = {
  'Audio Player': 'Trình phát Audio',
  'Video Player': 'Trình phát Video',
  Play: 'Tiếp tục phát',
  Pause: 'Tạm dừng',
  Replay: 'Phát lại',
  'Current Time': 'Thời gian hiện tại',
  Duration: 'Độ dài',
  'Remaining Time': 'Thời gian còn lại',
  'Stream Type': 'Kiểu Stream',
  LIVE: 'LIVE',
  Loaded: 'Đã tải',
  Progress: 'Tiến trình',
  'Progress Bar': 'Thanh tiến trình',
  'progress bar timing: currentTime={1} duration={2}': '{1} của {2}',
  Fullscreen: 'Toàn màn hình',
  'Non-Fullscreen': 'Thoát toàn màn hình',
  'Exit-Fullscreen': 'Thoát toàn màn hình',
  'Exit Fullscreen': 'Thoát toàn màn hình',
  Mute: 'Tắt tiếng',
  Unmute: 'Bật tiếng',
  'Playback Rate': 'Tỉ lệ phát lại',
  Subtitles: 'Phụ đề',
  'subtitles off': 'tắt phụ đề',
  Captions: 'Chú thích',
  'captions off': 'tắt chú thích',
  Chapters: 'Chương',
  Descriptions: 'Mô tả',
  'descriptions off': 'tắt mô tả',
  'Audio Track': 'Track âm thanh',
  'Volume Level': 'Mức âm lượng',
  'You aborted the media playback': 'Bạn đã hủy việc phát lại media.',
  'A network error caused the media download to fail part-way.':
    'Một lỗi mạng dẫn đến việc tải media bị lỗi.',
  'The media could not be loaded, either because the server or network failed or because the format is not supported.':
    'Video không tải được, mạng hay server có lỗi hoặc định dạng không được hỗ trợ.',
  'The media playback was aborted due to a corruption problem or because the media used features your browser did not support.':
    'Phát media đã bị hủy do một sai lỗi hoặc media sử dụng những tính năng trình duyệt không hỗ trợ.',
  'No compatible source was found for this media.':
    'Không có nguồn tương thích cho media này.',
  'The media is encrypted and we do not have the keys to decrypt it.':
    'Media đã được mã hóa và chúng tôi không có để giải mã nó.',
  'Playback cannot continue. No available working or supported playlists.':
    'Không thể tiếp tục phát lại. Không có danh sách phát đang hoạt động hoặc được hỗ trợ.',
  'Play Video': 'Phát Video',
  Close: 'Đóng',
  'Close Modal Dialog': 'Đóng cửa sổ',
  'Modal Window': 'Cửa sổ',
  'This is a modal window': 'Đây là một cửa sổ',
  'This modal can be closed by pressing the Escape key or activating the close button.':
    'Cửa sổ này có thể thoát bằng việc nhấn phím Esc hoặc kích hoạt nút đóng.',
  ', opens captions settings dialog': ', mở hộp thoại cài đặt chú thích',
  ', opens subtitles settings dialog': ', mở hộp thoại cài đặt phụ đề',
  ', opens descriptions settings dialog': ', mở hộp thoại cài đặt mô tả',
  ', selected': ', đã chọn',
  'captions settings': 'cài đặt chú thích',
  'subtitles settings': 'cài đặt phụ đề',
  'descriptions settings': 'cài đặt mô tả',
  Text: 'Văn bản',
  White: 'Trắng',
  Black: 'Đen',
  Red: 'Đỏ',
  Green: 'Xanh lá cây',
  Blue: 'Xanh da trời',
  Yellow: 'Vàng',
  Magenta: 'Đỏ tươi',
  Cyan: 'Lam',
  Background: 'Nền',
  Window: 'Cửa sổ',
  Transparent: 'Trong suốt',
  'Semi-Transparent': 'Bán trong suốt',
  Opaque: 'Mờ',
  'Font Size': 'Kích cỡ phông chữ',
  'Text Edge Style': 'Dạng viền văn bản',
  None: 'None',
  Raised: 'Raised',
  Depressed: 'Depressed',
  Uniform: 'Uniform',
  Dropshadow: 'Dropshadow',
  'Font Family': 'Phông chữ',
  'Proportional Sans-Serif': 'Proportional Sans-Serif',
  'Monospace Sans-Serif': 'Monospace Sans-Serif',
  'Proportional Serif': 'Proportional Serif',
  'Monospace Serif': 'Monospace Serif',
  Casual: 'Casual',
  Script: 'Script',
  'Small Caps': 'Small Caps',
  Reset: 'Đặt lại',
  'restore all settings to the default values':
    'khôi phục lại tất cả các cài đặt về giá trị mặc định',
  Done: 'Xong',
  'Caption Settings Dialog': 'Hộp thoại cài đặt chú thích',
  'Beginning of dialog window. Escape will cancel and close the window.':
    'Bắt đầu cửa sổ hộp thoại. Esc sẽ thoát và đóng cửa sổ.',
  'End of dialog window.': 'Kết thúc cửa sổ hộp thoại.',
  Quality: 'Chất lượng',
  'Seek forward 10 seconds': 'Tua đi 10s',
  'Seek back 10 seconds': 'Tua lại 10s',
};
export const VIDEO_OPTIONS_VOD: object = {
  language: 'vi',
  languages: {
    vi: LANGUAGE,
  },
  responsive: true,
  aspectRatio: '16:9',
  controls: true,
  poster: '/images/default-poster-horizontal.png',
  textTrackSettings: false,
  bigPlayButton: false,
  controlBar: {
    pictureInPictureToggle: false,
    children: [
      'playToggle',
      'volumePanel',
      'currentTimeDisplay',
      'durationDisplay',
      'progressControl',
      'customControlSpacer',
      'playbackRateMenuButton',
      'chaptersButton',
      'descriptionsButton',
      'subsCapsButton',
      'audioTrackButton',
      'fullscreenToggle',
    ],
  },
  dnaConfig: {},
  html5: {
    hls: {
      overrideNative: true,
    },
    nativeAudioTracks: false,
    nativeVideoTracks: false,
  },
};
export const VIDEO_OPTIONS_TRAILER: object = {
  language: 'vi',
  languages: {
    vi: LANGUAGE,
  },
  responsive: true,
  aspectRatio: '16:9',
  controls: true,
  poster: '/images/default-poster-horizontal.png',
  textTrackSettings: false,
  bigPlayButton: false,
  controlBar: {
    pictureInPictureToggle: false,
    children: ['volumePanel'],
  },
};
export const VIDEO_OPTIONS_LIVE: object = {
  fluid: true,
  language: 'vi',
  languages: {
    vi: LANGUAGE,
  },
  responsive: true,
  autoplay: false,
  muted: true,
  disablePictureInPicture: true,
  aspectRatio: '16:9',
  controls: true,
  poster: '/images/default-poster-horizontal.png',
  textTrackSettings: false,
  bigPlayButton: false,
  controlBar: false,
  dnaConfig: {},
  html5: {
    vhs: {
      enableLowInitialPlaylist: false,
      maxPlaylistRetries: 1,
    },
  },
};
export const LIST_CHANNEL_SOCKET: Array<string> = [
  'binh-duong-2',
  'vtc3-hd',
  'ha-tinh',
  'fox-sports-3',
  'fox-sports-2',
  'fox-sports-hd',
  'v-league-1',
  'v-league-2',
  'v-league-3',
  'v-league-4',
  'copa-america-1',
  'copa-america-2',
  'vtv5-hd',
  'vtv6-hd',
  'serie-a-1',
  'serie-a-2',
  'serie-a-3',
  'serie-a-4',
  'serie-a-5',
  'serie-a-6',
  'serie-a-7',
  'serie-a-8',
  'serie-a-9',
  'serie-a-10',
  'afc-1',
  'afc-2',
  'afc-3',
  'afc-4',
  'afc-5',
  'afc-6',
  'afc-7',
  'afc-8',
  'afc-9',
  'afc-10',
  'htv9-hd',
  'youth-league-1',
  'youth-league-2',
  'uefa-1',
  'uefa-2',
  'uefa-3',
  'uefa-4',
  'uefa-5',
  'uefa-6',
  'uefa-7',
  'uefa-8',
  'uefa-9',
  'uefa-10',
];
export const P2P_VIDEOJS_DNA_PLUGIN = `/js/p2p/videojs/videojs-hls-dna-plugin.js?srKey=${process.env.MESH_P2P_KEY}`;
export const P2P_VIDEOJS_PLUGIN = '/js/p2p/videojs/videojs-hlsjs-plugin.js';
export const P2P_VIDEOJS_GRAPH = '/js/p2p/graphs.js';
export const MESSAGE_NOT_SUPPORTED =
  'Playback cannot continue. No available working or supported playlists.';
export const VIDEO_JS_SDKS = {
  VIDEOJS: '/js/videoJs/video.min.js',
  VHS: '/js/videoJs/videojs-http-streaming.min.js',
  DASH: '/js/dash/dash.all.min.js',
  VIDEOJS_DASH: '/js/dash/videojs-dash.js',
};
