export type TrackingAppId =
  | 'HOME'
  | 'DIAL'
  | 'SEARCH'
  | ''
  | 'dynamic'
  | 'thanh-toan'
  | 'MEGA'
  | 'PAIRING'
  | 'IPTV'
  | 'WEBVIEW'
  | 'WEBVIEW_VQMM'
  | 'SUBSCRIPTION'
  | 'VNG'
  | 'playzone'
  | 'Login'
  | 'YearInReview'
  | 'CHATBOT'
  | 'ACCOUNT';
export type TrackingAppName =
  | 'HOME'
  | 'ERROR'
  | 'BOOT SCRIPT'
  | 'DIAL/ FingerPrint'
  | 'SEARCH'
  | ''
  | 'dynamic'
  | 'Thanh toán'
  | 'MEGA'
  | 'PAIRING'
  | 'IPTV'
  | 'WEBVIEW'
  | 'WEBVIEW_VQMM'
  | 'SUBSCRIPTION'
  | 'VNG'
  | 'Kho game'
  | 'Login'
  | 'YearInReview'
  | 'CHATBOT'
  | 'ACCOUNT';

export type TrackingScreen =
  | 'SIGNUP'
  | 'Error'
  | 'BootScript'
  | 'StartApplication'
  | 'Login'
  | 'ResumeApplication'
  | 'Nofitication'
  | 'Payment'
  | 'QRCode'
  | 'Search'
  | 'Account'
  | 'Setting'
  | 'ImageError'
  | 'PageError'
  | ''
  | 'OK'
  | 'Popup'
  | 'Back'
  | 'Game'
  | 'Announcement'
  | 'CheckDeviceDRM'
  | 'MainMenu'
  | 'Buffering'
  | 'Registration'
  | 'Enrolled'
  | 'CancelBilling'
  | 'Function'
  | 'ModifiedInformation'
  | 'Logout'
  | 'ChangeVideoQuality'
  | 'ConnectionSetting'
  | 'ChannelList'
  | 'VNG'
  | 'Notification'
  | 'BroadcastSchedule'
  | 'ScheduleList'
  | 'PingChannel'
  | 'PingVOD'
  | 'PingTrailer'
  | 'PingLiveshow'
  | 'PingPremiere'
  | 'PingPreview'
  | 'ChangeAudio'
  | 'ChangeResolution'
  | 'LoadFirstFrame'
  | 'ServiceList'
  | 'MethodList'
  | 'PaymentConfirmation'
  | 'Access'
  | 'AccessProfile'
  | 'RegisterProfile'
  | 'ModifiedProfile'
  | 'RemovedProfile'
  | 'ListBlockDisplay'
  | 'UnsubscriptionClick'
  | 'UnsubscriptionConfirm'
  | 'UnsubcribeSuccessfully'
  | 'UnsubcribeFailed'
  | 'None'
  | 'Inbox'
  | 'CodecDeviceInformation'
  | 'PingPreviewLive'
  | 'PingPreviewShow'
  | 'GetDRMKey'
  | 'Backdrop'
  | 'ListHighlightItem'
  | 'ChatBot'
  | 'Fail'
  | 'Success'
  | 'PageLogin'
  | 'CancelOTP'
  | 'LimitDevice'
  | 'Buffering'
  | 'AddAlarm'
  | 'RemoveAlarm'
  | 'Function'
  | 'SideTagButton'
  | 'ModifiedInformation'
  | 'DeactivateAccount'
  | 'SubscriptionList'
  | 'UnsubscriptionClick'
  | 'UnsubscriptionConfirm'
  | 'UnsubcribeSuccessfully'
  | 'UnsubcribeFailed';

export type TrackingEvent =
  | 'SignupSuccess'
  | 'SignupFail'
  | 'ErrorBooting'
  | 'Script_NTP'
  | 'CloseApplication'
  | 'StartApplication'
  | 'LoginSuccess'
  | 'LoginFail'
  | 'ResumeApplication'
  | 'RefreshPage'
  | 'EnterNotification'
  | 'EnterPayment'
  | 'EnterQRCode'
  | 'EnterSearch'
  | 'EnterAccount'
  | 'EnterGame'
  | 'EnterSetting'
  | 'Error'
  | 'LimitDevice'
  | 'ReDirectYTB'
  | 'LoadPageError'
  | 'Confirmed'
  | 'ShowPopup'
  | 'Announcement'
  | 'ReceivedSuccessfully'
  | 'ReceivedFailed'
  | 'CheckDeviceDRM'
  | 'ShowSuccessfully'
  | 'ShowFailed'
  | 'BACK'
  | 'ChangeModule'
  | 'Search'
  | 'Access'
  | 'EnterMainMenu'
  | 'Subscribed'
  | 'Unsubscribed'
  | 'EnterDetail'
  | 'RequestPackage'
  | 'IPTVRequestPackage'
  | 'EnterPlaylist'
  | 'Ping'
  | 'StartBuffering'
  | 'EndBuffering'
  | 'RegisteredSuccess'
  | 'RegisteredFailed'
  | 'TimeOut'
  | 'EnrolledSuccess'
  | 'EnrolledFailed'
  | 'EnrolledTimeOut'
  | 'CancelExtraRegister'
  | 'CancelExtraUnRegister'
  | 'AccessItem'
  | 'ChangeInformation'
  | 'RemoveMethodPayment'
  | 'ChangePassword'
  | 'Logout'
  | 'StartMovie'
  | 'StartTrailer'
  | 'StopMovie'
  | 'StopTrailer'
  | 'PauseMovie'
  | 'PauseTrailer'
  | 'ResumeMovie'
  | 'ResumeTrailer'
  | 'NextMovie'
  | 'NextTrailer'
  | 'ChangeVideoQuality'
  | 'RemoveMultiDevices'
  | 'EnterIPTV'
  | 'StartChannel'
  | 'StopChannel'
  | 'StartTimeshift'
  | 'StopTimeshift'
  | 'ShowSchedule'
  | 'ExitSchedule'
  | 'ShowChannelList'
  | 'EnterDetailLiveShow'
  | 'StartLiveShow'
  | 'StopLiveShow'
  | 'PlaybackError'
  | 'ChangeAudio'
  | 'ChangeResolution'
  | 'LoadFirstFrame'
  | 'RetryPlayer'
  | 'AccessPage'
  | 'ChangeSubtitles'
  | 'EnterWebview'
  | 'AccessProfile'
  | 'RegisteredProfile'
  | 'ModifiedProfile'
  | 'RemovedProfile'
  | 'Login'
  | 'Seek'
  | 'SkipForward'
  | 'SkipBack'
  | 'Share'
  | 'Comment'
  | 'Like'
  | 'LoadBlockDisplay'
  | 'OnClick'
  | 'UnsubcribePackage'
  | 'ConfirmedPopup'
  | 'GetDRMKeyFailed'
  | 'GetDRMKeySuccessfully'
  | 'Initial'
  | 'Retry'
  | 'CodecDeviceInformation'
  | 'PlayAttemp'
  | 'SeekTimeshift'
  | 'PauseTimeshift'
  | 'ResumeTimeshift'
  | 'ShowBackdrop'
  | 'LoginMethod'
  | 'CancelLogin'
  | 'GetStatusConfig'
  | 'FIDRespond'
  | 'ChangeTokenSignal'
  | 'ThirdPartyRespond'
  | 'CheckAPIGetUserInfo'
  | 'FirstLoad'
  | 'LoadHighlightItem'
  | 'EnterChatBot'
  | 'Request'
  | 'Feedback'
  | 'Buffering'
  | 'AddAlarm'
  | 'RemoveAlarm'
  | 'DeactivateAccount'
  | 'ButtonClick'
  | 'AccessItem'
  | 'ModifiedInformation'
  | 'DeactivateSuccess';

export interface TrackingParams {
  platform?: string;
  device?: string;
  device_id?: string;
  device_name?: string;
  model_name?: string;
  deviceManufacture?: string;
  user_id?: string;
  user_phone?: string;
  user_session?: string;
  timestamp?: string;
  FPTPlay_version?: string;
  Firmware_version?: string;
  environment?: string;
  os_version?: string;
  Netmode?: string;
  Session?: string;

  AppId?: TrackingAppId;
  AppName?: TrackingAppName;
  Screen?: TrackingScreen;
  Event?: TrackingEvent;
  BoxTime?: string;
  ErrCode?: string;
  ErrMessage?: string;
  ItemId?: string;
  ItemName?: string;
  Url?: string;
  Key?: string;
  LogId?: string;

  Status?: string;
  AppSession?: string;
  HotkeySession?: string;
  MenuSession?: string;
  SubMenuId?: string;
  playing_session?: string;
  function_session?: string;
  Keyword?: string;
  Genre?: string;
  IDRelated?: string;

  Bandwidth?: string;
  BufferLength?: string;
  isLastEpisode?: string;
  TotalEpisode?: string;
  ChapterID?: string;
  PublishCountry?: string;
  BlockPosition?: string;
  Credit?: string;
  DateStamp?: string;
  StartTime?: string;
  Duration?: string;
  ElapsedTimePlaying?: string;
  RealTimePlaying?: string;
  Folder?: string;
  FType?: string;
  PlayerName?: string;
  BusinessPlan?: string;
  Method?: string;
  PromoCode?: string;
  MonthPrepaid?: string;
  Price?: string;
  isLinkDRM?: string;
  Directors?: string;
  VideoQuality?: string;
  GroupChannel?: string;
  Multicast?: string;
  isLandingPage?: string;
  IsLive?: string;
  utm?: string;
  utm_session?: string;
  is_utm_inApp?: string;
  CDNName?: string;
  Bitrate?: string;
  Resolution?: string;
  Audio?: string;
  Subtitle?: string;
  isManual?: string;
  PlaylistID?: string;
  EpisodeID?: string;
  contract?: string;
  ip?: string;
  RefItemId?: string;
  RefEpisodeID?: string;
  RefPlaylistID?: string;
  profile_id?: string;
  profile_session?: string;
  StreamBandwidthAudio?: string;
  StreamBandwidth?: string;
  Dimension?: string;
  Seek?: string;
  SkipBack?: string;
  SkipForward?: string;
  Share?: string;
  Comment?: string;
  TotalByteLoaded?: string;
  DRMPartner?: string;
  Initial?: string;
  Retry?: string;
  isPreAdv?: string;
  ClickToPlayTime?: string;
  InitPlayerTime?: string;
  AudioCodec?: string;
  VideoCodec?: string;
  StreamProfile?: string;
  hdrType?: string;
  UrlMode?: string;
  StreamAudioProfile?: string;
  IssueId?: string;
  ErrUrl?: string;
  ErrHeader?: string;
  AppSource?: string;
  BrowserUrl?: string;
  Position?: string;
  AdsTime?: string;
  chat_session?: string;
  is_recommend?: string;
  login_session?: string;
  tabId?: string;
}

export interface UserParams {
  user_id?: string;
  user_phone?: string;
}
